config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'registrations'}

  resources :journey, only: [:index]
  resources :banks, only: [:index, :show]
  resources :insurances, only: [:index, :show]
  resources :registration_offices, only: [:index, :show]

  resources :questions, only: [:new, :set_session_questions]
  post 'set_session', to: 'questions#set_session_questions', as: 'set_session_questions'
  post 'questions_create', to: 'questions#create', as: 'questions_create'
  resources :appointments, only: [:edit, :update, :create, :show]
  resources :questions

  get 'tv_license', to: 'pages#tv_license'
  get 'req_index', to: 'pages#req_index'

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
  post 'insurance/:id/create', to: 'insurances#create', as: 'insurances_create'
  patch 'insurance/:id/update', to: 'insurances#update', as: 'insurances_update'
  patch 'insurance/:id/delete', to: 'insurances#destroy', as: 'insurances_delete'

  post 'banks/:id/create', to: 'banks#create', as: 'banks_create'
  patch 'banks/:id/update', to: 'banks#update', as: 'banks_update'
  patch 'banks/:id/delete', to: 'banks#destroy', as: 'banks_delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :registration_office
  has_many_attached :photos

  def not_booked?
    self.user.nil?
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :choices
    has_many :users, through: :choices

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user

  def self.new_chatroom(user)
    chatroom_number = Chatroom.count + 1
    chatroom = Chatroom.new(name: "Chat with Hans - #{chatroom_number}")
    chatroom.user = user
    chatroom.save!
    chatroom
  end
end

app/models/insurance.rb
class Insurance < ApplicationRecord
    has_many :choices
    has_many :users, through: :choices
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  def self.welcome_message(user, chatroom)
    message = Message.new(content: "Hello #{user.first_name}! How can I help you today?")
    hans = User.find(1)
    message.user = hans
    message.chatroom = chatroom
    message.save!
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  def self.save_question(session, user)
    question = Question.new
    question.employment_status = session[:employment_status]
    question.annual_gross_income_range = session[:annual_gross_income_range] == 'Yes'
    question.phone_number = session[:phone_number]
    question.arrivel_date = session[:arrivel_date]
    question.date_of_birth = session[:date_of_birth]
    question.german_level = session[:german_level]
    question.duration = session[:duration] == 'Yes'
    question.user = user
    question.save!

    user.address = session[:address]
    user.save!
  end

end

app/models/registration_office.rb
class RegistrationOffice < ApplicationRecord
  has_many :appointments, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :appointments
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :user_choices
  has_many :chatrooms
end

app/models/user_choice.rb
class UserChoice < ApplicationRecord
  belongs_to :bank, optional: true
  belongs_to :insurance, optional: true
  belongs_to :user
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  def index
    @insurances = Insurance.all
    @user_answers = current_user.questions.first
    @public_insurances = Insurance.where(private: false)
    @private_insurances = Insurance.where(private: true)
    @employment_status = @user_answers.employment_status
    @annual_gross_income_range = @user_answers.annual_gross_income_range
    age = Date.today.year - @user_answers.date_of_birth.year
    if @annual_gross_income_range == 'f' || (@employment_status == "Student" && age < 30)
      @insurance = @public_insurances
      @type = "public health care."
    elsif age <= 35 && @annual_gross_income_range == 't'
      @insurance = @private_insurances
      @type = "private health care as it is cheaper in the long term."
    else
      @insurance = @insurances
      @type = "either public or private health insurance."
    end
    @new = current_user.user_choices.first.nil?
  end

  def create
    user = current_user
    insurance = Insurance.find(params[:id])
    @user_choice = UserChoice.new
    @user_choice.user = user
    @user_choice.insurance = insurance
    @user_choice.save!
    redirect_to journey_index_path
  end

  def update
    insurance = Insurance.find(params[:id])
    @user_choice = UserChoice.where(user: current_user).first
    @user_choice.insurance = insurance
    @user_choice.save!
    redirect_to journey_index_path
  end

  def destroy
    @user_choice = UserChoice.where(user: current_user).first
    @user_choice.insurance = nil
    @user_choice.save!
    redirect_to journey_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/journey_helper.rb
module JourneyHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/insurances/index.html.erb
<h1 class="page-header-text text-shadow">Health Insurance <i>(Krankenversicherung</i>) </h1>

<div class="container">
  <div class="info-paragraph">
    <p>If you are already researching health insurance companies, you likely know the importance of a solid insurance plan. Admittedly, purchasing a policy can be confusing, and it is going to take a lot of browsing, detailed reading, and comparing insurance policies before you decide on the right one.</p>


    <p>Once you sign up for a health insurance policy in Berlin (whether private or public), you will receive an insurance card in the mail, which you have to present whenever seeking medical treatment. Health insurance covers the majority of your basic medical needs, and it is usually all you need. </p>
  </div>
</div>

<div class="container">
  <div class="results-paragraph">
    <h3>Based on your income and age, we recommend that you go with <strong><%= @type %></strong> Here are our favorite options:</h3>
  </div>
</div>

<div class="flex-container card-container">
    <% @insurance.each do |insurance| %>
      <div class="flex-container nu2-card insurance-card">
        <%= image_tag(insurance.image) %>
        <h2 class="text-shadow"><%=insurance.name %></h2>
        <p><%= insurance.summary %></p>
        <%= link_to 'Select Insurance', insurances_create_path(insurance), class: "btn-gradient-yellow-insurance", method: :post if @new %>
        <%= link_to 'Select Insurance', insurances_update_path(insurance), class: "btn-gradient-yellow-insurance", method: :patch unless @new %>
      </div>
    <% end %>
</div>

<div class="back-btn-container">
  <%= link_to "<< Back to Required Tasks", req_index_path, class: "btn-back" %>
</div>