config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'registrations'}

  resources :journey, only: [:index]
  resources :banks, only: [:index, :show]
  resources :insurances, only: [:index, :show]
  resources :registration_offices, only: [:index, :show]

  resources :questions, only: [:new, :set_session_questions]
  post 'set_session', to: 'questions#set_session_questions', as: 'set_session_questions'
  post 'questions_create', to: 'questions#create', as: 'questions_create'
  resources :appointments, only: [:edit, :update, :create, :show]
  resources :questions

  get 'tv_license', to: 'pages#tv_license'
  get 'req_index', to: 'pages#req_index'

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
  post 'insurance/:id/create', to: 'insurances#create', as: 'insurances_create'
  patch 'insurance/:id/update', to: 'insurances#update', as: 'insurances_update'
  patch 'insurance/:id/delete', to: 'insurances#destroy', as: 'insurances_delete'

  post 'banks/:id/create', to: 'banks#create', as: 'banks_create'
  patch 'banks/:id/update', to: 'banks#update', as: 'banks_update'
  patch 'banks/:id/delete', to: 'banks#destroy', as: 'banks_delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :registration_office
  has_many_attached :photos

  def not_booked?
    self.user.nil?
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :choices
    has_many :users, through: :choices

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user

  def self.new_chatroom(user)
    chatroom_number = Chatroom.count + 1
    chatroom = Chatroom.new(name: "Chat with Hans - #{chatroom_number}")
    chatroom.user = user
    chatroom.save!
    chatroom
  end
end

app/models/insurance.rb
class Insurance < ApplicationRecord
    has_many :choices
    has_many :users, through: :choices
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  def self.welcome_message(user, chatroom)
    message = Message.new(content: "Hello #{user.first_name}! How can I help you today?")
    hans = User.find(1)
    message.user = hans
    message.chatroom = chatroom
    message.save!
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  def self.save_question(session, user)
    question = Question.new
    question.employment_status = session[:employment_status]
    question.annual_gross_income_range = session[:annual_gross_income_range] == 'Yes'
    question.phone_number = session[:phone_number]
    question.arrivel_date = session[:arrivel_date]
    question.date_of_birth = session[:date_of_birth]
    question.german_level = session[:german_level]
    question.duration = session[:duration] == 'Yes'
    question.user = user
    question.save!

    user.address = session[:address]
    user.save!
  end

end

app/models/registration_office.rb
class RegistrationOffice < ApplicationRecord
  has_many :appointments, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :appointments
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :user_choices
  has_many :chatrooms
end

app/models/user_choice.rb
class UserChoice < ApplicationRecord
  belongs_to :bank, optional: true
  belongs_to :insurance, optional: true
  belongs_to :user
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController

  def index
    @banks = Bank.all
    @user_answers = current_user.questions.first
    @german_level = @user_answers.german_level
    @duration = @user_answers.duration
    if @duration == "t"
      @bank = @german_level == 'Beginner' ? Bank.find_by(name: 'Deutsche Bank') : Bank.find_by(name: 'Commerzbank')
      @alternative_banks = @banks.select{|bank| bank != @bank}
    else
      @bank = Bank.find_by(name: 'N26')
      @alternative_banks = @banks.select{|bank| bank != @bank}
    end
    @new = current_user.user_choices.first.nil?
  end

  def create
    user = current_user
    bank = Bank.find(params[:id])
    @user_choice = UserChoice.new
    @user_choice.user = user
    @user_choice.bank = bank
    @user_choice.save!
    redirect_to journey_index_path
  end

  def update
    bank = Bank.find(params[:id])
    @user_choice = UserChoice.where(user: current_user).first
    @user_choice.bank = bank
    @user_choice.save!
    redirect_to journey_index_path
  end

  def destroy
    @user_choice = UserChoice.where(user: current_user).first
    @user_choice.bank = nil
    @user_choice.save!
    redirect_to journey_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/journey_helper.rb
module JourneyHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/banks/index.html.erb
<h1 class="page-header-text text-shadow">Getting a Bank Account</h1>

<div class="container">
  <div class="info-paragraph">
    <p>
      When moving to Germany, it is very important to have (preferably free!) access to your funds. There are few things more frustrating than incurring expensive bank transaction fees, ATM charges, and delays in money transfers. On top of this, having a German bank account is often an important requirement for renting an apartment, signing up for a phone/internet package and getting paid by your employer. As such, setting up a German bank account as soon as possible is definitely a priority when moving to Germany! In Germany, there are a number of traditional banking options as well as an array of modern online banks. We have profiled a number of these below, highlighting their respective pros and cons to give you a clear idea of which is the best bank in Germany for your situation.
    </p>
  </div>
</div>

<div class="container">
  <div class="results-paragraph">
    <h3>Based on your <strong>planned duration of stay and language skills</strong>, we recommend the below option(s) for you.</h3>
  </div>
</div>

<div class="flex-container">
  <div class="bank-recommendation-card card-product-infos text-center">
    <h2 class="card-bank-name-inverted"><%= "Our favorite for you:" %></h2>
    <%= image_tag(@bank.image) %>
    <h2 class="card-bank-name-inverted"><%= @bank.name%></h2>
    <p class="card-bank-text-inverted"><%= @bank.summary %></p>
    <%= link_to 'Select Bank', banks_create_path(@bank), class: "btn-gradient-yellow", method: :post if @new %>
    <%= link_to 'Select Bank', banks_update_path(@bank), class: "btn-gradient-yellow", method: :patch unless @new %>
  </div>

  <% @alternative_banks.each do |bank| %>
    <div class="nu2-card card-bank card-product-infos text-center">
      <h2 class="card-bank-name"><%= "Alternative option:"%></h2>
      <%= image_tag(bank.image) %>
      <h2 class="card-bank-name"><%= bank.name%></h2>
      <p class="card-bank-text"><%= bank.summary %></p>
      <%= link_to 'Select Bank', banks_create_path(bank), class: "btn-gradient-yellow", method: :post if @new %>
      <%= link_to 'Select Bank', banks_update_path(bank), class: "btn-gradient-yellow", method: :patch unless @new %>
    </div>
  <% end %>
</div>


<div class="back-btn-container">
  <%= link_to "<< Back to Required Tasks", req_index_path, class: "btn-back" %>
</div>