config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'registrations'}

  resources :journey, only: [:index]
  resources :banks, only: [:index, :show]
  resources :insurances, only: [:index, :show]
  resources :registration_offices, only: [:index, :show]

  resources :questions, only: [:new, :set_session_questions]
  post 'set_session', to: 'questions#set_session_questions', as: 'set_session_questions'
  post 'questions_create', to: 'questions#create', as: 'questions_create'
  resources :appointments, only: [:edit, :update, :create, :show]
  resources :questions

  get 'tv_license', to: 'pages#tv_license'
  get 'req_index', to: 'pages#req_index'

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
  post 'insurance/:id/create', to: 'insurances#create', as: 'insurances_create'
  patch 'insurance/:id/update', to: 'insurances#update', as: 'insurances_update'
  patch 'insurance/:id/delete', to: 'insurances#destroy', as: 'insurances_delete'

  post 'banks/:id/create', to: 'banks#create', as: 'banks_create'
  patch 'banks/:id/update', to: 'banks#update', as: 'banks_update'
  patch 'banks/:id/delete', to: 'banks#destroy', as: 'banks_delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :registration_office
  has_many_attached :photos

  def not_booked?
    self.user.nil?
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :choices
    has_many :users, through: :choices

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user

  def self.new_chatroom(user)
    chatroom_number = Chatroom.count + 1
    chatroom = Chatroom.new(name: "Chat with Hans - #{chatroom_number}")
    chatroom.user = user
    chatroom.save!
    chatroom
  end
end

app/models/insurance.rb
class Insurance < ApplicationRecord
    has_many :choices
    has_many :users, through: :choices
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  def self.welcome_message(user, chatroom)
    message = Message.new(content: "Hello #{user.first_name}! How can I help you today?")
    hans = User.find(1)
    message.user = hans
    message.chatroom = chatroom
    message.save!
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  def self.save_question(session, user)
    question = Question.new
    question.employment_status = session[:employment_status]
    question.annual_gross_income_range = session[:annual_gross_income_range] == 'Yes'
    question.phone_number = session[:phone_number]
    question.arrivel_date = session[:arrivel_date]
    question.date_of_birth = session[:date_of_birth]
    question.german_level = session[:german_level]
    question.duration = session[:duration] == 'Yes'
    question.user = user
    question.save!

    user.address = session[:address]
    user.save!
  end

end

app/models/registration_office.rb
class RegistrationOffice < ApplicationRecord
  has_many :appointments, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :appointments
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :user_choices
  has_many :chatrooms
end

app/models/user_choice.rb
class UserChoice < ApplicationRecord
  belongs_to :bank, optional: true
  belongs_to :insurance, optional: true
  belongs_to :user
end

app/controllers/journey_controller.rb
class JourneyController < ApplicationController
  def index
    @user = current_user
    unless @user.user_choices.first.nil?
      @bank = @user.user_choices.first.bank
      @insurance = @user.user_choices.first.insurance
    end
    @appointment = @user.appointments.first
    unless @appointment.nil? || @appointment.registration_office.nil?
      @booking_date_time = @appointment.date
      @date = @booking_date_time.strftime("#{@booking_date_time.day.ordinalize} %B")
      @time = @appointment.date.strftime('%l:%M %p')
      office = @appointment.registration_office
      @markers = [{
        lat: office.latitude,
        lng: office.longitude,
        info_window: render_to_string(partial: "/registration_offices/info_window",
        locals: { office: office })
      }]
      @user_marker = {
        lat: current_user.latitude,
        lng: current_user.longitude,
        image_url: helpers.asset_url('home_icon.png')
    }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/journey_helper.rb
module JourneyHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/journey/_form.html.erb
<div class="container">
  <%= simple_form_for :appointment do |f| %>
    <%= f.input :photos,label:false, as: :file %>
  <% end %>
</div>

app/views/journey/index.html.erb
<div class="container">
  <h1 class="page-header-text text-shadow">My Portal</h1>
  <div class="grid-container portal-grid">
    <%# <div id="progress-bar" class="journey-boxes"> %>
      <div class="progress-bar-outer">
        <span class="progress-bar-mainbar" id="main-bar">0%</span>
      </div>
    <%# </div> %>

    <div class="selected-information-box journey-boxes registration-box">
      <% if @appointment %>
        <div class="registration-information-box">
          <h4 class="task"><%= @appointment.registration_office.office_name %></h4>
          <div class="registration-details">
            <a href="https://www.google.com/maps/dir/<%= current_user.address %>/<%= @appointment.registration_office.address %>" target="_blank"><%= @appointment.registration_office.address %></a>
            <p><%= "#{@date}#{} at #{@time}" %></p>
          </div>
          <div id="map"
            data-markers="<%= @markers.to_json %>"
            data-user-marker="<%= @user_marker.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
          <div class="buttons-group-user">
            <button class="user-portal-button portal-update">Update</button>
            <button class="user-portal-button portal-delete">Delete</button>
          </div>
        </div>
      <% else %>
        <%= link_to "Book Appointment", registration_offices_path, class: "btn-gradient-purple button-span"%>
        <%= image_tag('apartment.png', class: "holding-img", id: "apartment") %>
      <% end %>
    </div>

    <div class="selected-information-box">

      <div class="user-card-selected-info journey-boxes">
        <% if @bank %>
            <div class="user-card-header">
              <%= image_tag @bank.image, class: "logo-img" %>
              <p class="task"><%= @bank.name%></p>
            </div>
            <div class="details">
              <%= link_to "Update", banks_path, class: "user-portal-button portal-update"%>
              <%= link_to 'Delete', banks_delete_path(@bank.id), class: "user-portal-button portal-delete", method: :patch %>
            </div>
        <% else %>
          <%= link_to "Select Bank", banks_path, class: "btn-gradient-purple button-span"%>
          <%= image_tag('banking.png', class: "holding-img") %>
        <% end %>
      </div>

      <div class="user-card-selected-info journey-boxes">
        <% if @insurance %>
          <div class="user-card-header">
                <%= image_tag @insurance.image, class: "logo-img" %>
                <p class="task"><%= @insurance.name%></p>
              </div>
          <div class="details">
            <%= link_to "Update", insurances_path, class: "user-portal-button portal-update"%>
            <%= link_to 'Delete', insurances_delete_path(@insurance.id), class: "user-portal-button portal-delete", method: :patch %>
          </div>
        <% else %>
          <%= link_to "Select Insurance", insurances_path, class: "btn-gradient-purple button-span"%>
          <%= image_tag('insurance3.png', class: "holding-img") %>
        <% end %>
      </div>

      <div class="user-card-selected-info journey-boxes">
        <div class="container">
            <p class="upload-header">No documents currently required.</p>
            <%= render "form", appointment: @appointment %>
        </div>
      </div>

    </div>
  </div>
</div>
<br>
<div class="back-btn-container">
  <%= link_to "<< Back to Required Tasks", req_index_path, class: "btn-back" %>
</div>