config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'registrations'}

  resources :journey, only: [:index]
  resources :banks, only: [:index, :show]
  resources :insurances, only: [:index, :show]
  resources :registration_offices, only: [:index, :show]

  resources :questions, only: [:new, :set_session_questions]
  post 'set_session', to: 'questions#set_session_questions', as: 'set_session_questions'
  post 'questions_create', to: 'questions#create', as: 'questions_create'
  resources :appointments, only: [:edit, :update, :create, :show]
  resources :questions

  get 'tv_license', to: 'pages#tv_license'
  get 'req_index', to: 'pages#req_index'

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
  post 'insurance/:id/create', to: 'insurances#create', as: 'insurances_create'
  patch 'insurance/:id/update', to: 'insurances#update', as: 'insurances_update'
  patch 'insurance/:id/delete', to: 'insurances#destroy', as: 'insurances_delete'

  post 'banks/:id/create', to: 'banks#create', as: 'banks_create'
  patch 'banks/:id/update', to: 'banks#update', as: 'banks_update'
  patch 'banks/:id/delete', to: 'banks#destroy', as: 'banks_delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :registration_office
  has_many_attached :photos

  def not_booked?
    self.user.nil?
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :choices
    has_many :users, through: :choices

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user

  def self.new_chatroom(user)
    chatroom_number = Chatroom.count + 1
    chatroom = Chatroom.new(name: "Chat with Hans - #{chatroom_number}")
    chatroom.user = user
    chatroom.save!
    chatroom
  end
end

app/models/insurance.rb
class Insurance < ApplicationRecord
    has_many :choices
    has_many :users, through: :choices
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  def self.welcome_message(user, chatroom)
    message = Message.new(content: "Hello #{user.first_name}! How can I help you today?")
    hans = User.find(1)
    message.user = hans
    message.chatroom = chatroom
    message.save!
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  def self.save_question(session, user)
    question = Question.new
    question.employment_status = session[:employment_status]
    question.annual_gross_income_range = session[:annual_gross_income_range] == 'Yes'
    question.phone_number = session[:phone_number]
    question.arrivel_date = session[:arrivel_date]
    question.date_of_birth = session[:date_of_birth]
    question.german_level = session[:german_level]
    question.duration = session[:duration] == 'Yes'
    question.user = user
    question.save!

    user.address = session[:address]
    user.save!
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :appointments
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :user_choices
  has_many :chatrooms
end

app/models/user_choice.rb
class UserChoice < ApplicationRecord
  belongs_to :bank, optional: true
  belongs_to :insurance, optional: true
  belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/journey_helper.rb
module JourneyHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <div class="d-flex flex-column min-vh-100">
      <%= render 'shared/navbar' %>
      <%# Hans is a chat room created as demonstration, to reactivate them please uncomment the line below. %>
      <%# render 'shared/chat' if current_user %>
      <%= render 'shared/flashes' %>
      <div class="flex-grow-1">
        <%= yield %>
      </div>
      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
        </div>
        <div>
          I <i class="fas fa-heart"></i> Berlin.
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%# BANNER %>

<div class="banner flex-container">
  <div class="home-image">
    <%= image_tag 'bureaucracy.jpg'  %>
  </div>

  <div class="banner-text-container">
    <div>
      <h1 class="text-shadow call-to-action" id="call-to-action-header">Nü2 Berlin?</h1>
      <p class="text-shadow call-to-action" id="call-to-action-text">We can help. Hack German bureaucracy with our services.</p>
      <div class="home-button-container flex-container">
        <%= link_to "GET STARTED", new_question_path, class: "btn-flat", id: "call-to-action-btn" unless current_user %> <br>
        <%= link_to "Already a member?", new_user_session_path unless current_user%>
      </div>
    </div>
  </div>
</div>

<%# CARDS ON LANDING PAGE %>
<div class="flex-container card-container">

  <div class="flex-container card-product nu2-card home-card">
    <%= image_tag 'telescope.png'  %>
    <div class="card-product-infos">
      <h2 class="text-shadow">Fulsome Support</h2>
      <ul>
        <li>City registration, banking, insurance and more! </li>
        <li>Track all information in place.</li>
      </ul>
    </div>
  </div>

  <div class="flex-container card-product nu2-card home-card">
    <%= image_tag 'ridin.png' %>
    <div class="card-product-infos">
      <h2 class="text-shadow">Fast and Free</h2>
      <ul>
        <li>Services are completely free.</li>
        <li>Book your appointments online.</li>
        <li>We're available to chat 24/7!</li>
      </ul>
    </div>
  </div>

  <div class="flex-container card-product nu2-card home-card">
    <%= image_tag 'peace.png' %>
    <div class="card-product-infos">
      <h2 class="text-shadow">Friendly Service</h2>
      <ul>
        <li>We offer customized solutions.</li>
        <li>We speak English, Mandarin, German and French!</li>
      </ul>
    </div>
  </div>

</div>

<div class="flex-container">
  <%= link_to "TAKE OUR QUIZ", new_question_path, class: "btn-back" unless current_user %>
</div>

app/views/pages/req_index.html.erb
<h1 class="page-header-text text-shadow">Based on your answers, here are your required tasks:</h1>
<div class="card-square-container flex-container">

  <%= link_to(registration_offices_path) do %>
    <div class="card-square nu2-card">
      <h4 class="card-square-infos">Apartment Registration</h4>
      <%= image_tag 'apartment.png'  %>
    </div>
  <% end %>

  <%= link_to(insurances_path) do %>
    <div class="card-square nu2-card">
      <h4 class="card-square-infos">Health Insurance</h4>
      <%= image_tag 'insurance5.png' %>
    </div>
  <% end %>

  <%= link_to(banks_path) do %>
    <div class="card-square nu2-card">
      <h4 class="card-square-infos">Banking</h4>
      <%= image_tag 'payments.png' %>
    </div>
  <% end %>

  <%= link_to(tv_license_path) do %>
    <div class="card-square nu2-card">
      <h4 class="card-square-infos">TV Licensing</h4>
      <%= image_tag 'radio.png' %>
    </div>
  <% end %>

</div>

<div class="flex-container">
  <%= link_to "TAKE ME TO MY PORTAL", journey_index_path, class: "btn-back" %>
</div>

app/views/pages/tv_license.html.erb
<h1 class="page-header-text text-shadow">German TV License Fee <i>(Rundfunkbeitrag</i>)</h1>

  <div class="container">
    <div class="info-paragraph">
      <h3>What is this <i>Rundfunkbeitrag</i> exactly?</h3>
      <p>The <i>Rundfunkbeitrag</i> can be defined as the broadcasting fee or TV/radio tax in Germany. Each household in Germany ought to pay this fee, set at 17,50€ per month. It roughly translates to “global broadcasting contribution”.

      This contribution supports public TV & radio channels so they can produce independent & quality content, free of any governmental or other private influence. In 2020, it was 8,1 billions euros that were raised thanks to this system.

      Early versions of the broadcasting fee can be traced as far as 1924, and it has evolved over the years. Its mission has stayed the same even if technology & devices have advanced.</p>
    </div>
  </div>

    <%# <div class="bot">
      <%= image_tag 'bot5.png'  %>
    <%# </div> %>

<h2 class="page-header-text">Frequently Asked Questions:</h2>
<div class="card-square-container flex-container">
  <div class="flex-card-item-3">
    <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <h2>Is the German TV tax mandatory?</h2>
        </div>
        <div class="flip-card-back">
          <p>Yes. All German households have to pay this fee, although some exemptions are applicable depending on your handicap or social situation.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="flex-card-item-3">
    <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <h2>Does I need to pay the tax if I don’t understand German?</h2>
        </div>
        <div class="flip-card-back">
          <p>Yes. The inability to speak German does not exempt you from paying the broadcasting fee.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="flex-card-item-3">
    <div class="flip-card flex-card-item-3">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <h2>Do I need to pay German TV tax if I’m an exchange student?</h2>
        </div>
        <div class="flip-card-back">
          <p>Yes. During your time in Germany, when becoming a resident, you also liable for it. You can apply for exemption if you receive welfare support in the form of AföG, <i>Berufsausbildungsbeihilfe</i> or <i>Ausbildungsgeld</i>.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="flex-card-item-3">
    <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <h2>Where do I find my <i>Beitragsnummer?</i></h2>
        </div>
        <div class="flip-card-back">
          <p>You can find your Beitragsnummer subscription confirmation or on the payment reminders you have received. It has a 9-number format.</p>
        </div>
      </div>
    </div>
  </div>


  <div class="flex-card-item-3">
    <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <h2>Which channels are financed by the <i>Rundfunkbeitrag?</i></h2>
        </div>
        <div class="flip-card-back">
          <p>ARD, ZDF (second TV channel), ARTE, Phoenix, 3sat, KiKA, ONE and all channels belonging to Deutschland Radio.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="flex-card-item-3">
    <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <h2>Can I put this fee off in taxes?</h2>
        </div>
        <div class="flip-card-back">
          <p>No, unfortunately not.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="back-btn-container">
  <%= link_to "<< Back to Required Tasks", req_index_path, class: "btn-back" %>
</div>

app/views/shared/_card.html.erb
<div class="section-container">
  <div class="card-product">
    <div style="text-align: center">
      <%= image_tag 'telescope.png'  %>
    </div>
    <div class="card-product-infos">
        <h2 class="header-shadow">Fullsome Support</h2>
        <ul>
          <li>"City address registration, health insurance, bank account, and more!" </li>
          <li>"Gather and keep track of all your information in one place."</li>
          <li>"We've done the research so you don't have to."
        </ul>
    </div>
  </div>

app/views/shared/_chat.html.erb
<div class="user-chat">
  <% unless current_user.id == 1 %>
    <div id="main" class="chat-page" data-current-user="<%= current_user.first_name %>">
      <div>
        <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
        <% @chatroom.messages.each do |message| %>
            <i class="author <%= message.user == current_user ? "my-message-author" : "your-message-author" %>">
                <span><%= message.user.first_name %></span>
                <small><%= message.created_at.strftime(" %l:%M%p ") %></small><br>
            </i>
            <div class="message-container <%= message.user == current_user ? "my-message" : "your-message" %>"  id="message-<%= message.id %>" data-user="<%= message.user.first_name %> ">
            <p><%= message.content %></p>
            </div>
        <% end %>
        </div>
        <div id="send-message">
            <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
            <%= f.input :content, label: false, placeholder: "#{@chatroom.name}" %>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
        </div>
        <div>
          I <i class="fas fa-heart"></i> Berlin.
        </div>
      </div>

app/views/shared/_hans.html.erb
<li>
  <% if current_user.id == 1 %>
    <%= link_to "Available Chats", chatrooms_path, class: "nav-link", style: "font-weight:bold;" %>
  <% else %>
    <div id="bot-link">
      <%= image_tag "https://res.cloudinary.com/dz9aqljih/image/upload/v1630483947/nu2_images/bot4_ljor1s.png", class: "nav-link", id: "bot" %> | Help
    </div>
  <% end %>
</li>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-nu2">
  <%= link_to "Nü2", root_path, class: "navbar-nu2-logo" %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%# Hans is a chat room created as demonstration, to reactivate them please uncomment the line below. %>
        <%= render 'shared/hans' %>
        <li>
          <%= link_to "My Portal", journey_index_path, class: "nav-link", style: "font-weight:bold;" %>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link", style: "font-weight:bold;" %>
        </li>
      <% else %>
        <li class="navbar-button">
          <%= link_to "Log in", new_user_session_path, class: "btn-hollow" unless @reg_flow %>
        </li>
      <% end %>
    </ul>
  </div>
</div>